# Stats 21 - HW 3

# Colin Doherty

Homework copyright Miles Chen. Problems have been adapted from the exercises in Think Python 2nd Ed by Allen B. Downey.

The questions have been entered into this document. You will modify the document by entering your code.

Make sure you run the cell so the requested output is visible. Export it as an HTML file and then print to PDF.

**Homework is an opportunity to practice coding and to practice problem solving.**

**Doing exercises is where you will do most of your learning.**

**Using AI or copying someone else's solutions takes away your learning opportunities. It is also academic dishonesty.**

## Reading

- Chapter 10 - Dictionaries
- Chapter 12 - Tuples
- Chapter 13 - Files

Please keep up with the reading. The chapters are short.

### Modified Exercise based on Think Python 2ed. Chap 11, Section 10, Exercise 11.1

<https://greenteapress.com/thinkpython2/html/thinkpython2012.html>

Write a function that reads the words in `words.txt` and stores them as keys in a dictionary. It doesn't matter what the values are. Then you can use the `in` operator as a fast way to check whether a string is in the dictionary.

In [147]:
def make_word_dict():
    dict = {}
    with open('words.txt', 'r') as file:
        for word in file:
            key = word[:-2]
            dict[key] = 1
    return dict
    


In [148]:
word_dict = make_word_dict()
"hello" in word_dict

True

### Modified Exercise based on Think Python 2ed. Chap 11, Section 10, Exercise 11.4

<https://greenteapress.com/thinkpython2/html/thinkpython2012.html>

In HW2 Exercise 10.7, you created a function called `has_duplicates()`. It takes a list as a parameter and returns `True` if there is any object that appears more than once in the list.

Use a dictionary to write a faster, simpler version of `has_duplicates()`.

In [149]:
def has_duplicates(t):
    dict = {}
    for item in t:
        if item in dict:
            return True
        else:
            dict[item] = True
    
    return False


In [150]:
has_duplicates(['a','b','b','c'])

True

In [151]:
has_duplicates(['a','b','c','a'])

True

### Modified Exercise based on Think Python 2ed. Chap 11, Section 10, Exercise 11.5

<https://greenteapress.com/thinkpython2/html/thinkpython2012.html>

A Caesar cipher is a weak form of encryption that involves 'rotating' each letter by a fixed number of places. To rotate a letter means to shift it through the alphabet, wrapping around to the beginning if necessary. "A" rotated by 3 is "D". "Z" rotated by 1 is "A".

Two words are "rotate pairs" if you can rotate one of them and get the other. For example, "cheer" rotated by 7 is "jolly".

Write a script that reads in the wordlist `words.txt` and finds all the rotate pairs of words that are 5 letters or longer.

One function that could be helpful is the function `ord()` which converts a character to a numeric code. Keep in mind that numeric codes for uppercase and lowercase letters are different.

Some hints:

- you can write helper functions, such as a function that will rotate a letter by a certain number and/or another function that will rotate a word by a number of letters
- to keep your script running quickly, you should use the wordlist dictionary from exercise 11.1

In [152]:
# write your code here.

In [153]:
has_duplicates(['a','b','b','c'])

True

### Modified Exercise based on Think Python 2ed. Chap 12, Section 10, Exercise 12.2

<https://greenteapress.com/thinkpython2/html/thinkpython2013.html>

Write a program that reads a word list from a file (see Section 9.1) and finds all the sets of words that are anagrams.

After finding all anagram sets, print the list of all anagram sets that have 6 or more entries in it.

Here is an example of what the output might look like:

~~~
['abets', 'baste', 'bates', 'beast', 'beats', 'betas', 'tabes']
['acers', 'acres', 'cares', 'carse', 'escar', 'races', 'scare', 'serac']
['acred', 'arced', 'cadre', 'cared', 'cedar', 'raced']
...
~~~

Hint:

First traverse the entire wordlist to build a dictionary that maps from a collection of letters to a list of words that can be spelled with those letters. The question is, how can you represent the collection of letters in a way that can be used as a key? i.e. The word "eat" and the word "tea" should be in a list associated with a key ('a','e','t').

In [ ]:
file = open('words.txt', 'r')

dict = {}
anagrams = []

for line in file:
    word = line[:-2]
    if len(word)<6:
        continue;
    letters = [*word]
    letters.sort()
    key = tuple(letters)
    if(not key in dict):
        dict[key] = [word]
    elif not word in dict[key]:
        dict[key].append(word)
        anagrams.append(dict[key])

file.close()

print([x for x in anagrams][0:10])

['abaser', 'abreas', 'arabes']
['ablutio', 'abutilo', 'bailout']
['ablution', 'abutilon']
['accedin', 'acciden']
['accouter', 'accoutre']
['accurse', 'accuser', 'reaccus']
['abreact', 'acerbat', 'bearcat', 'bractea', 'cabaret']
['abreacte', 'acerbate']
['abreactin', 'acerbatin']
['acetoni', 'aconite', 'catenoi']
['accusatio', 'acoustica']
['abroac', 'acroba']
['acrosti', 'acrotis', 'actoris']
['aconiti', 'actinoi', 'cationi', 'inactio']
['aconit', 'actino', 'action', 'atonic', 'cation', 'coatin', 'contai']
['aconit', 'actino', 'action', 'atonic', 'cation', 'coatin', 'contai']
['acrosti', 'acrotis', 'actoris']
['accentua', 'acutance']
['adjour', 'adjuro']
['administrato', 'adminstratio']
['adversit', 'advertis']
['affectation', 'affectionat']
['ageniz', 'agnize']
['agnosti', 'agonist']
['airbrus', 'airburs']
['aiblin', 'albini', 'bailin']
['abilit', 'albiti']
['acclai', 'alcaic', 'cicala']
['aileron', 'alienor']
['airflo', 'alifor']
['algerin', 'aligner', 'engrail', 'gnarlie', 'lagerin'

### NumPy Exercises

For the following exercises, be sure to print the desired output. You will not receive credit for problems that do not print the desired output.

Some of these exercises will require the use of functions in numpy that may not have been covered in class. Look up documentation on how to use them. I always recommend checking the official reference at https://numpy.org/doc/stable/reference/index.html 

In [155]:
import numpy as np
rng = np.random.default_rng(seed = 1)

#### Exercise NP.1:

Task: Create an array `b` of 10 random integers selected between 0-99

Desired output: `[47 51 75 95  3 14 82 94 24 31]` of course yours might be different

In [156]:
b = rng.integers(0, 99, 10)

In [157]:
b

array([46, 50, 74, 94,  3, 14, 81, 93, 24, 30])

#### NP.1b:

Task: reverse the elements in `b`. Hint: Try slicing the array, but backwards

In [158]:
b[-1::-1]

array([30, 24, 93, 81, 14,  3, 94, 74, 50, 46])

#### NP.2a:

Task: Create an array `c` of 1000 random values selected from a normal distribution centered at 100 with sd = 15, rounded to 1 decimal place. Print only the first 10 values.

Desired output: `[ 92.1  83.9 113.   65.5 126.2  88.6 104.8  96.3 121.9  69.1]` of course your values may be different

In [159]:
c = rng.normal(100, 15, 1000)
print(c[0:10])

[106.69561859  91.94570147 108.71677156 105.46858594 104.41198745
 100.42633362 108.2006948   88.95318869  97.55635078  92.76821031]


#### NP.2b:

Perform a Shapiro-Wilk test to see if the values in c come from a normal distribution. Report the p-value and appropriate conclusion.

Look up `scipy.stats.shapiro` for usage and details.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html

In [160]:
from scipy.stats import shapiro

test = shapiro(c)
print(test.pvalue)
if(test.pvalue < 0.05):
    print("data is probably not normal")
else:
    print("Cannot confidently say data isn't normal")

0.784042777523317
Cannot confidently say data isn't normal


#### NP.2c:

Identify and print the values in `c` that are more than 3 standard deviations from the mean of `c`. Report the proportion of values that are more than 3 sd from the mean.

Desired output: `[ 54.1 ... 148.3 ]`

`0.32 of the values are beyond 3 sd from the mean.`

In [161]:
# hard-coded from ealier
sd = 15
mean = 100

low_outliers = c < mean-3*sd
print(c[low_outliers])
print(f"proportion: {low_outliers.mean()}")

[53.79733361 46.76792544]
proportion: 0.002


#### NP.3:

Task: Make a 3x3 identity matrix called `I3`

Desired output: 

~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
~~~

In [162]:
I3 = np.matrix([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 0]
])

#### NP.4a:

Task: Make a 10x10 array of values 1 to 100. Call it X

Desired output: 

~~~
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
 ~~~

In [163]:
arr = []
for row in range(0, 10):
    tens = row*10
    arr.append(range(tens+1, tens+11))

X = np.matrix(arr)
print(X)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


#### NP.4b:

Task: Make a copy of X, call it Y (1 line). Replace all values in Y that are not squares with 0 (1 line). see `numpy.isin()`

Desired output: 

~~~
[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
...
 [  0   0   0   0   0   0   0   0   0 100]]
 ~~~

In [164]:
Y = X.copy()

Y[~np.isin(Y, [x**2 for x in range(1,11)])] = 0
print(Y)

[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
 [  0   0   0   0   0  36   0   0   0   0]
 [  0   0   0   0   0   0   0   0  49   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  64   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 81   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 100]]


#### NP.5:

Task: Use `np.tile()` to tile a 2x2 diagonal matrix of integers to make a checkerboard pattern. Call the matrix `checkers`

Desired output: 

~~~
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 ...
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
 ~~~

In [165]:
checkers = np.tile([1, 0], [8, 4])
print(checkers)

[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]


#### NP.6:

Task: convert the values in `f_temp` from Farenheit to celsius. The conversion is subtract 32, then multiply by 5/9. Round to 1 decimal place.

Desired output: 

~~~
[[21.1 21.7 22.2 22.8 23.3 23.9]
 ...
 [34.4 35.  35.6 36.1 36.7 37.2]]
~~~

In [166]:
# do not modify
f_temp  = np.arange(70,100).reshape((5,6))

In [167]:
c_temp = ((f_temp-32)*5/9).round(1)
print(c_temp)

[[21.1 21.7 22.2 22.8 23.3 23.9]
 [24.4 25.  25.6 26.1 26.7 27.2]
 [27.8 28.3 28.9 29.4 30.  30.6]
 [31.1 31.7 32.2 32.8 33.3 33.9]
 [34.4 35.  35.6 36.1 36.7 37.2]]


#### NP.7:

Task: Convert values in the matrix `x` into z-scores by column, call it matrix `z`. That is: each column should have a mean of 0 and std of 1. (subtract the column mean, and divide by the column std). (not required, but see if you can do this in one line)

Print the column means and column std to show that they have been standardized.

Desired output: 

~~~
[[ 0.41148428  1.04307072 -1.43031951]
 [-0.34069129 -1.14825432 -0.77270135]
...
 [-0.60705751 -1.08536687 -0.57430135]
 [-1.28156585 -0.81250928  1.52877401]]
 
[-1.16573418e-16  7.77156117e-17  1.44328993e-16]
[1. 1. 1.]
~~~

In [168]:
# do not modify
rng = np.random.default_rng(seed = 100)
x = rng.integers(0, 100, size = 30).reshape(10,3)

In [169]:
mean = x.mean()
sd = x.std()

Z = (X - mean)/sd
print(Z)

[[-1.81066679 -1.77624346 -1.74182014 -1.70739682 -1.67297349 -1.63855017
  -1.60412685 -1.56970353 -1.5352802  -1.50085688]
 [-1.46643356 -1.43201023 -1.39758691 -1.36316359 -1.32874027 -1.29431694
  -1.25989362 -1.2254703  -1.19104697 -1.15662365]
 [-1.12220033 -1.087777   -1.05335368 -1.01893036 -0.98450704 -0.95008371
  -0.91566039 -0.88123707 -0.84681374 -0.81239042]
 [-0.7779671  -0.74354378 -0.70912045 -0.67469713 -0.64027381 -0.60585048
  -0.57142716 -0.53700384 -0.50258051 -0.46815719]
 [-0.43373387 -0.39931055 -0.36488722 -0.3304639  -0.29604058 -0.26161725
  -0.22719393 -0.19277061 -0.15834729 -0.12392396]
 [-0.08950064 -0.05507732 -0.02065399  0.01376933  0.04819265  0.08261598
   0.1170393   0.15146262  0.18588594  0.22030927]
 [ 0.25473259  0.28915591  0.32357924  0.35800256  0.39242588  0.4268492
   0.46127253  0.49569585  0.53011917  0.5645425 ]
 [ 0.59896582  0.63338914  0.66781246  0.70223579  0.73665911  0.77108243
   0.80550576  0.83992908  0.8743524   0.90877573]
 

#### NP.8:

Task: Convert values in the matrix `x` into scaled values from 0 to 10. That is take each column and scale values linearly so that the largest value is 10, and the smallest value in the column is 0. Round results to 2 decimal places. Call the result `y`

(Not required, but see if you can do the calculations in one line.)

Desired output: 

~~~
[[0.67 0.88 0.  ]
 [0.41 0.09 0.2 ]
 ...
 [0.   0.66 0.02]
 [0.39 0.61 0.59]]
 ~~~

In [170]:
# do not modify
rng = np.random.default_rng(seed = 100)
x = rng.integers(0, 100, size = 30).reshape(10,3)

In [171]:
y = x.copy()
for i in range(0, x.shape[1]):
    column = x[:, i]
    y[:, i] = column/column.max()*10

#optional print x for reference
#print(x)
print(y)

[[ 7  8  1]
 [ 6  0  3]
 [ 4  0  6]
 [ 9 10  6]
 [ 4  8 10]
 [ 9  0  7]
 [ 7  1  5]
 [10  7  3]
 [ 3  6  1]
 [ 5  6  6]]


#### NP.9:

Task: Replace all NaN values in the matrix `x` with 0.

Desired output: 

~~~
[[76. 83. 12.]
 [59.  8.  0.]
 [44.  0. 58.]
 [ 0. 94. 59.]]
~~~

In [172]:
# do not modify
rng = np.random.default_rng(seed = 100)
x = rng.integers(0, 100, size = 12).reshape(4,3).astype('float')
row = np.array([1, 2, 3])
col = np.array([2, 1, 0])
x[row, col] = np.nan

In [173]:
x = np.nan_to_num(x, 0)
print(x)

[[76. 83. 12.]
 [59.  8.  0.]
 [44.  0. 58.]
 [ 0. 94. 59.]]
